# docker/mathlibs/libsci/Dockerfile.zendnn.cray.aocc.mkl.onednn.gcc.base
FROM scratch

# Assuming LibSci is available
ENV LIBSCIROOT=/opt/cray/pe/libsci
ENV LD_LIBRARY_PATH=$LIBSCIROOT/lib:$LD_LIBRARY_PATH

