# docker/mathlibs/mkl/Dockerfile.mkl
FROM ubuntu:20.04

# Install necessary utilities
RUN apt-get update && apt-get install -y wget tar gnupg
ENV PATH=$PATH:/usr/bin

# Install Intel MKL

RUN wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB && \
    apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB && \
    echo "deb https://apt.repos.intel.com/mkl all main" | tee /etc/apt/sources.list.d/intel-mkl.list && \
    apt update && apt install -y intel-mkl-64bit-2020.0-088
    #source /opt/intel/mkl/bin/mklvars.sh intel64


RUN ls -alh
RUN ls /opt/intel/mkl/

ENV MKLROOT=/opt/intel/oneapi/mkl/latest
ENV LD_LIBRARY_PATH=$MKLROOT/lib/intel64:$LD_LIBRARY_PATH
ENV MKL_THREADING_LAYER=GNU
ENV USE_MKL=1
ENV BLAS=MKL
ENV CMAKE_PREFIX_PATH="/opt/intel/oneapi/mkl:$CMAKE_PREFIX_PATH"

