# docker/compilers/cray/Dockerfile.aocc.mkl.onednn.gcc.base
FROM docker/base:latest

# Add commands to setup Cray environment
ENV CC=cc
ENV CXX=CC
ENV FC=ftn

# Set environment variables for Cray compiler and modules

