FROM nvcr.io/nvidia/cuda-dl-base:25.03-cuda12.8-devel-ubuntu24.04 AS builder
RUN apt update && \
   apt install -y python3 \
   apt install -y  python-is-python3 python3-pip
WORKDIR /tmp
ARG DEEPSPEED_VERSION=0.17.0
RUN git clone --recursive https://github.com/horovod/horovod horovod \
&&  cd horovod \
&&  git checkout v0.28.0 \
&&  git submodule sync && git submodule update --init --recursive 
WORKDIR /tmp/horovod
ENV CC=mpicc CXX=mpicxx HOROVOD_WITH_MPI=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_GLOO=1 HOROVOD_BUILD_CUDA_CC_LIST=70,80,90 
RUN pip install .

WORKDIR /tmp
ARG TARGETPLATFORM
#COPY triton-1.1.1-cp38-cp38-linux_aarch64.whl .
SHELL ["/bin/bash", "-c"]
#RUN if [ "$TARGETPLATFORM" == "linux/arm64" ]; then pip install --verbose --prefix=/software /tmp/triton-1.1.1-cp38-cp38-linux_aarch64.whl; else pip install --verbose --prefix=/software triton ; fi
RUN pip install --prefix=/software tensorboardX boto3 h5py
RUN env MPICC=mpicc pip install --prefix=/software mpi4py

WORKDIR /tmp
RUN git clone -b v$DEEPSPEED_VERSION https://github.com/microsoft/DeepSpeed.git DeepSpeed-$DEEPSPEED_VERSION \
&&  cd DeepSpeed-$DEEPSPEED_VERSION \
&&  pip install --prefix=/software . 

ENV PYTHONPATH=/software/lib/python3.8/site-packages:${PYTHONPATH}
WORKDIR /workspace
RUN rm -rf /tmp/*
 
