FROM nvcr.io/nvidia/cuda-dl-base:25.03-cuda12.8-devel-ubuntu24.04 AS builder
RUN apt update && \
   apt install -y python3 && \
   apt install -y  python-is-python3 && \
   apt install -y python3-pip && \
   apt install -y cmake
RUN pip install --prefix=/software numpy && \ 
    pip install --prefix=/software --index-url https://download.pytorch.org/whl/cu128 torch==2.7.0
ENV PYTHONPATH=/software/local/lib/python3.12/dist-packages
WORKDIR /tmp
ARG DEEPSPEED_VERSION=0.17.0
RUN git clone --recursive https://github.com/horovod/horovod horovod \
&&  cd horovod \
&&  git checkout v0.28.0 \
&&  git submodule sync && git submodule update --init --recursive 
WORKDIR /tmp/horovod
ENV CC=mpicc CXX=mpicxx HOROVOD_MPICXX_SHOW="mpicxx --show" HOROVOD_WITH_MPI=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_GLOO=1 HOROVOD_BUILD_CUDA_CC_LIST=70,80,90 
RUN sed -i 's/set(CMAKE_CXX_STANDARD 14)/set(CMAKE_CXX_STANDARD 17)/g' ./CMakeLists.txt && \
    sed -i 's/set(CMAKE_CXX_STANDARD 14)/set(CMAKE_CXX_STANDARD 17)/g' ./horovod/torch/CMakeLists.txt
RUN python setup.py clean && \
    CXXFLAGS="-include 'stdexcept'" python setup.py install --prefix=/software
ARG TARGETPLATFORM
RUN if [ "$TARGETPLATFORM" == "linux/arm64" ]; then cp -r build/lib.linux-aarch64-cpython-312/horovod /software/local/lib/python3.12/dist-packages/; else cp -r build/lib.linux-x86_64-cpython-312/horovod /software/local/lib/python3.12/dist-packages/triton ; fi
RUN pip install --prefix=/software pyyaml cffi==1.17 && \
    pip install --prefix=/software cloudpickle
WORKDIR /tmp
#COPY triton-1.1.1-cp38-cp38-linux_aarch64.whl .
SHELL ["/bin/bash", "-c"]
#RUN if [ "$TARGETPLATFORM" == "linux/arm64" ]; then pip install --verbose --prefix=/software /tmp/triton-1.1.1-cp38-cp38-linux_aarch64.whl; else pip install --verbose --prefix=/software triton ; fi
RUN pip install --prefix=/software tensorboardX boto3 h5py
RUN env MPICC=mpicc pip install --prefix=/software mpi4py

WORKDIR /tmp
RUN git clone -b v$DEEPSPEED_VERSION https://github.com/microsoft/DeepSpeed.git DeepSpeed-$DEEPSPEED_VERSION \
&&  cd DeepSpeed-$DEEPSPEED_VERSION \
&&  pip install --prefix=/software . 
ENV PATH=/software/local/bin:${PATH}
WORKDIR /workspace
RUN rm -rf /tmp/*
 
