# docker/dnn/onednn/Dockerfile.onednn

# Use a base image that includes the necessary tools
FROM ubuntu:20.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages including wget
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    git \
    cmake \
    wget \
    python3-dev \
    python3-pip \
    curl \
    ca-certificates

# Upgrade pip and install necessary Python packages
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install numpy pyyaml setuptools cmake cffi typing_extensions future six requests dataclasses

# Download and install Intel oneDNN
RUN git clone --depth 1 https://github.com/oneapi-src/oneDNN.git && \
    cd oneDNN/ && mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DDNNL_CPU_RUNTIME=OMP -DDNNL_BUILD_EXAMPLES=ON && \
    make -j $(nproc) && make install


# Set environment variables for oneDNN
ENV DNNL_ROOT=/usr/local
ENV LD_LIBRARY_PATH=$DNNL_ROOT/lib:$LD_LIBRARY_PATH
ENV LIBRARY_PATH=$DNNL_ROOT/lib:$LIBRARY_PATH
ENV C_INCLUDE_PATH=$DNNL_ROOT/include:$C_INCLUDE_PATH
ENV CPLUS_INCLUDE_PATH=$DNNL_ROOT/include:$CPLUS_INCLUDE_PATH
ENV USE_MKLDNN=1

# Verify installation
RUN ldconfig && \
    python3 -c "import ctypes; ctypes.CDLL('libdnnl.so').dnnl_version()"
