FROM nvcr.io/nvidia/pytorch:24.03-py3 AS base

RUN apt-get update \
&&  DEBIAN_FRONTEND=noninteractive apt-get install -y ffmpeg 
WORKDIR /software
RUN  pip install -v --prefix=/software --verbose SoccerNet==0.1.8 
RUN  pip install -v --prefix=/software --verbose opencv-python
#==3.4.11.45
RUN  pip install -v --prefix=/software --verbose imutils 
RUN  pip install -v --prefix=/software --verbose moviepy 
RUN  mkdir /data
ENV PYTHONPATH=/software/lib/python3.8/site-packages:${PYTHONPATH}
ENV SOCCERNET_INSTALL_DIR=/software
COPY download_data.py /data/download_data.py
